model_name: ablation_Model_EdgeCycle_0th
file_name: ablation_Model_EdgeCycle_0th
num_layers: 4
rep_dim: 64
dense_dim: 64
dropout: 0.5
# bn_eps: 0.00001
# bn_momentum: 0.05
cycle_sizes: [3,4,5,6] # [3,4,5,6,7,8,9,10,11,12,13,18] #[3, 4, 5, 6, 7, 8]
gather_overlap: 1
ptens_conv: False
readout: global_add_pool
