model_name: ablation_Model_Aut_on_branch_small
file_name: ablation_Model_Aut_on_branch_small
num_layers: 4
rep_dim: 64 #128
dense_dim: 64 #128
dropout: 0.0
num_channels: 2
cycle_sizes: [5,6] #[3, 4, 5, 6, 7, 8, 9, 10,11,12,13,18] #[3, 4, 5, 6, 7, 8, 11]
use_branched_5_cycles: True
gather_overlap: 2
ptens_conv: False
readout: global_add_pool