model_name: ablation_Model_Aut_edge2cycle_small
file_name: ablation_Model_Aut_edge2cycle_small
num_layers: 4
rep_dim: 64 #128
dense_dim: 64 #128
dropout: 0.0
num_channels: 2
cycle_sizes: [5, 6]
gather_overlap: 2
ptens_conv: False
readout: global_add_pool