model_name: Model_EdgeCycle_Aut_0th_batch_on_edge2cycle_small
file_name: Model_EdgeCycle_Aut_0th_batch_on_edge2cycle_small
num_layers: 4
rep_dim: 64
# dense_dim: 128
dropout: 0.5
num_channels: 4
cycle_sizes: [3, 4, 5, 6,]
ptens_conv: False
readout: global_add_pool